version: "3"
services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
  postgres4kitdm:
    build: postgres
    container_name: postgres4kitdm
    environment:
      - POSTGRES_PASSWORD=postgres4Docker
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}/server/backup/postgres:/dump"
      - "${PWD}/server/postgres:/var/lib/postgresql/data"
  arangodb4kitdm:
    image: arangodb
    container_name: arangodb4kitdm
    environment:
      - ARANGO_ROOT_PASSWORD=arangodb4Docker
    ports:
      - "8529:8529"
    volumes:
      - "${PWD}/server/backup/arangodb:/dump"
      - "${PWD}/server/arangodb:/var/lib/arangodb3"
  kitdm20:
    build: base-repo
    container_name: kitdm20
    links: 
      - postgres4kitdm
    ports:
      - "8090:8090"
    volumes:
      - "${PWD}/server/kitdm:/kitdm/archive"    
  metastore:
    build: metastore
    container_name: metastore
    links: 
      - postgres4kitdm
      - arangodb4kitdm
      - kitdm20
      - rabbitmq
    ports:
      - "8080:8080"

