CREATE DATABASE kitdm20;
CREATE DATABASE kitdm20_auth;
CREATE USER kitdm_admin WITH ENCRYPTED PASSWORD 'kitdm4Docker';
GRANT ALL PRIVILEGES ON DATABASE kitdm20 TO kitdm_admin;
GRANT ALL PRIVILEGES ON DATABASE kitdm20_auth TO kitdm_admin;

